"""Tests for full_analysis comprehensive song analyzer."""

import pytest

from code_music import Chord, Note, Song, Track, full_analysis


class TestFullAnalysis:
    """Test suite for full_analysis function."""

    def test_empty_song(self):
        """Test analysis of an empty song."""
        song = Song(title="Empty Test", bpm=120)
        report = full_analysis(song)

        assert "# Empty Test" in report
        assert "**BPM:** 120" in report
        assert "## Overview" in report
        assert "**Tracks:** 0" in report

    def test_single_track_song(self):
        """Test analysis of a simple single-track song."""
        song = Song(title="Simple Test", bpm=120, key_sig="C")
        track = song.add_track(Track(name="lead", instrument="piano"))
        track.add(Note("C", 5, 1.0))
        track.add(Note("E", 5, 1.0))
        track.add(Note("G", 5, 1.0))

        report = full_analysis(song)

        assert "# Simple Test" in report
        assert "## Overview" in report
        assert "## Track Analysis" in report
        assert "### lead (piano)" in report
        assert "**Notes:** 3" in report

    def test_song_with_chords(self):
        """Test analysis of a song with chord progressions."""
        song = Song(title="Chord Test", bpm=120, key_sig="C")
        chords = song.add_track(Track(name="chords", instrument="pad"))
        chords.add(Chord("C", "maj", octave=4, duration=4.0))
        chords.add(Chord("G", "maj", octave=4, duration=4.0))
        chords.add(Chord("A", "min", octave=4, duration=4.0))
        chords.add(Chord("F", "maj", octave=4, duration=4.0))

        report = full_analysis(song)

        assert "# Chord Test" in report
        assert "## Harmonic Analysis" in report
        assert "**Detected Key:**" in report
        assert "**Chords:** 4" in report

    def test_song_with_structure(self):
        """Test analysis detects song structure."""
        song = Song(title="Structure Test", bpm=120)

        # Intro
        intro = song.add_track(Track(name="intro_pad", instrument="pad"))
        intro.add(Chord("C", "maj", octave=4, duration=4.0))

        # Main section with more activity
        main = song.add_track(Track(name="main", instrument="piano"))
        for _ in range(8):
            main.add(Note("C", 5, 0.5))

        report = full_analysis(song)

        assert "## Structure" in report
        assert "**Sections:**" in report

    def test_full_analysis_markdown_format(self):
        """Test that output is valid markdown with expected sections."""
        song = Song(title="Format Test", bpm=120, key_sig="G")

        track = song.add_track(Track(name="melody", instrument="piano"))
        track.add(Note("G", 4, 1.0, velocity=100))
        track.add(Note("B", 4, 1.0, velocity=90))
        track.add(Note("D", 5, 1.0, velocity=80))

        report = full_analysis(song)

        # Check markdown structure
        assert report.startswith("# Format Test")
        assert "## Overview" in report
        assert "## Track Analysis" in report
        assert "*Generated by code-music*" in report

    def test_track_velocity_reporting(self):
        """Test that track velocities are reported."""
        song = Song(title="Velocity Test", bpm=120)
        track = song.add_track(Track(name="lead", instrument="piano"))

        for vel in [100, 80, 60]:
            track.add(Note("C", 5, 1.0, velocity=vel))

        report = full_analysis(song)

        assert "**Average Velocity:**" in report
        # Average should be 80
        assert "80" in report

    def test_pitch_range_reporting(self):
        """Test that pitch ranges are reported."""
        song = Song(title="Range Test", bpm=120)
        track = song.add_track(Track(name="lead", instrument="piano"))

        track.add(Note("C", 4, 1.0))  # MIDI 60
        track.add(Note("C", 6, 1.0))  # MIDI 84

        report = full_analysis(song)

        assert "**Pitch Range:**" in report
        # Range should span 24 semitones (2 octaves)
        assert "24" in report or "60" in report or "84" in report

    def test_duration_reporting(self):
        """Test that durations are reported."""
        song = Song(title="Duration Test", bpm=120)
        track = song.add_track(Track(name="lead", instrument="piano"))

        track.add(Note("C", 5, 2.0))
        track.add(Note("D", 5, 0.5))

        report = full_analysis(song)

        assert "**Duration:**" in report
        assert "**Average Duration:**" in report

    def test_song_with_multiple_tracks(self):
        """Test analysis of multi-track songs."""
        song = Song(title="Multi Track", bpm=120)

        lead = song.add_track(Track(name="lead", instrument="piano"))
        lead.add(Note("C", 5, 1.0))

        bass = song.add_track(Track(name="bass", instrument="bass"))
        bass.add(Note("C", 3, 1.0))

        drums = song.add_track(Track(name="drums", instrument="drums_kick"))
        drums.add(Note.rest(1.0))

        report = full_analysis(song)

        assert "### lead (piano)" in report
        assert "### bass (bass)" in report
        assert "### drums (drums_kick)" in report
        assert "**Tracks:** 3" in report

    def test_song_fingerprint_section(self):
        """Test that fingerprint section appears for songs with chords."""
        song = Song(title="Fingerprint Test", bpm=120, key_sig="C")
        chords = song.add_track(Track(name="harmony", instrument="pad"))
        chords.add(Chord("C", "maj", octave=4, duration=4.0))
        chords.add(Chord("F", "maj", octave=4, duration=4.0))
        chords.add(Chord("G", "maj", octave=4, duration=4.0))
        chords.add(Chord("C", "maj", octave=4, duration=4.0))

        report = full_analysis(song)

        # Should have fingerprint section
        assert "## Fingerprint" in report or "## Harmonic Analysis" in report

    def test_analysis_handles_rests(self):
        """Test that analysis properly handles rests."""
        song = Song(title="Rest Test", bpm=120)
        track = song.add_track(Track(name="lead", instrument="piano"))

        track.add(Note("C", 5, 1.0))
        track.add(Note.rest(1.0))
        track.add(Note("E", 5, 1.0))
        track.add(Note.rest(1.0))

        report = full_analysis(song)

        assert "**Rests:**" in report
        assert "2" in report  # Two rests


class TestFullAnalysisEdgeCases:
    """Edge case tests for full_analysis."""

    def test_very_long_song(self):
        """Test analysis handles long songs."""
        song = Song(title="Long Test", bpm=120)
        track = song.add_track(Track(name="lead", instrument="piano"))

        for i in range(100):
            track.add(Note("C", 5, 0.25))

        report = full_analysis(song)

        assert "# Long Test" in report
        assert "**Notes:** 100" in report

    def test_song_with_chords_and_melody(self):
        """Test analysis of song with both chords and melody."""
        song = Song(title="Combined Test", bpm=120, key_sig="C")

        chords = song.add_track(Track(name="harmony", instrument="pad"))
        chords.add(Chord("C", "maj7", octave=4, duration=4.0))
        chords.add(Chord("G", "dom7", octave=4, duration=4.0))

        melody = song.add_track(Track(name="lead", instrument="piano"))
        melody.add(Note("C", 5, 1.0))
        melody.add(Note("E", 5, 1.0))
        melody.add(Note("G", 5, 1.0))
        melody.add(Note("B", 5, 1.0))

        report = full_analysis(song)

        assert "### harmony (pad)" in report
        assert "### lead (piano)" in report
        assert "**Chords:** 2" in report or "**Notes:** 4" in report
