"""code-music: write code blocks, export audio."""

from .effects import (
    bandpass,
    chorus,
    compress,
    delay,
    distortion,
    flanger,
    gate,
    highpass,
    lfo_filter,
    limiter,
    lowpass,
    noise_sweep,
    pan,
    phaser,
    reverb,
    sidechain,
    stereo_width,
    tremolo,
    vibrato,
)
from .engine import (
    ARP_PATTERNS,
    CHORD_SHAPES,
    INTERVALS,
    SCALES,
    Beat,
    Chord,
    Note,
    Section,
    Song,
    Track,
    arp,
    chord_prog,
    crescendo,
    decrescendo,
    generate_melody,
    humanize,
    legato,
    pizzicato,
    prob,
    repeat,
    scale,
    staccato,
    transpose,
)
from .export import export_flac, export_mp3, export_ogg, export_wav
from .midi import export_midi
from .synth import Synth
from .voice import VoiceClip, VoiceTrack, detect_backends, list_voices
from .voice import generate as generate_voice

__all__ = [
    # engine
    "Note",
    "Chord",
    "Beat",
    "Track",
    "Song",
    "Section",
    "scale",
    "arp",
    "chord_prog",
    "crescendo",
    "decrescendo",
    "generate_melody",
    "humanize",
    "legato",
    "pizzicato",
    "prob",
    "repeat",
    "staccato",
    "transpose",
    "SCALES",
    "CHORD_SHAPES",
    "INTERVALS",
    "ARP_PATTERNS",
    # synth
    "Synth",
    # export
    "export_wav",
    "export_mp3",
    "export_ogg",
    "export_flac",
    "export_midi",
    # effects
    "reverb",
    "delay",
    "chorus",
    "distortion",
    "flanger",
    "phaser",
    "lowpass",
    "highpass",
    "bandpass",
    "compress",
    "limiter",
    "pan",
    "sidechain",
    "stereo_width",
    "tremolo",
    "vibrato",
    "lfo_filter",
    "gate",
    "noise_sweep",
    # voice
    "VoiceClip",
    "VoiceTrack",
    "generate_voice",
    "detect_backends",
    "list_voices",
]
