"""code-music: write code blocks, export audio."""

from importlib.metadata import PackageNotFoundError, version

try:
    __version__ = version("code-music")
except PackageNotFoundError:
    __version__ = "0.0.0-dev"

from .automation import Automation, EnvFollower, ModMatrix, song_append, song_extract, song_overlay
from .composition import (
    Bridge,
    Chorus,
    Intro,
    Outro,
    Verse,
    analyze_song,
    continue_melody,
    full_analysis,
    generate_arrangement,
    generate_fill,
    generate_intro,
    generate_outro,
    generate_riser,
    parse_song_dsl,
    quantize_track,
    render_preview,
    song_from_dsl_v2,
    song_map,
    song_summary,
    suggest_arrangement,
    tempo_map,
    to_abc,
    to_harmonic_rhythm,
    to_html,
    to_lead_sheet,
    to_piano_roll,
    to_sheet_music,
    to_spectrogram,
    to_svg_waveform,
    to_tab,
    to_track_waveforms,
)
from .effects import (
    EffectsChain,
    autotune,
    bandpass,
    bitcrush,
    chorus,
    compress,
    conv_reverb,
    # v151-152 spatial audio
    decode_bformat,
    # v151-152 spatial audio
    delay,
    distortion,
    encode_bformat,
    eq,
    flanger,
    gate,
    granular,
    highpass,
    lfo_filter,
    limiter,
    lowpass,
    multiband_compress,
    multitap_delay,
    noise_sweep,
    orbit,
    pan,
    phaser,
    reverb,
    ring_mod,
    sidechain,
    slapback,
    spatial_mix,
    spatial_pan,
    stereo_width,
    sum_bformat,
    tape_sat,
    tape_wow_flutter,
    tremolo,
    vibrato,
    vocoder,
    # v170 effects
    harmonic_exciter,
    lofi_vinyl,
    pitch_shift,
    rotary_speaker,
    shimmer_reverb,
    spring_reverb,
)
from .engine import (
    # composition helpers
    ARP_PATTERNS,
    CHORD_SHAPES,
    DOTTED_EIGHTH,
    DOTTED_HALF,
    DOTTED_QUARTER,
    DOTTED_SIXTEENTH,
    DOTTED_WHOLE,
    DOUBLE_DOTTED_HALF,
    DOUBLE_DOTTED_QUARTER,
    EIGHTH,
    # v170 dynamics
    F,
    FF,
    FFF,
    FFFF,
    FP,
    FZ,
    HALF,
    INTERVALS,
    MF,
    MP,
    P,
    PP,
    PPP,
    PPPP,
    QUARTER,
    RF,
    SCALES,
    SFP,
    SFZ,
    SIXTEENTH,
    SIXTY_FOURTH,
    THIRTY_SECOND,
    VELOCITY_CURVES,
    # durations
    WHOLE,
    Beat,
    Chord,
    Clip,
    ClipSlot,
    Note,
    # new
    PolyphonicTrack,
    SampleTrack,
    Section,
    Session,
    Song,
    Track,
    accelerando,
    analyze_progression,
    arp,
    bpm_ramp,
    chord_prog,
    crescendo,
    decrescendo,
    detect_key,
    doit,
    euclid,
    fall,
    flip,
    generate_melody,
    generate_song,
    grace_note,
    humanize,
    legato,
    mordent,
    pizzicato,
    prob,
    remix,
    repeat,
    ritardando,
    scale,
    shake,
    # articulations
    staccato,
    suggest_progression,
    transpose,
    # ornaments
    trill,
    # tuplets
    triplet,
    triplets,
    tuplet,
    tuplets,
    turn,
    upper_mordent,
    voice_lead,
    # v170 ornaments
    appoggiatura,
    glissando,
    # v170 articulations
    col_legno,
    con_sordino,
    dead_stroke,
    flutter_tongue,
    harmonics,
    muted,
    rim_click,
    senza_sordino,
    spiccato,
    sul_ponticello,
    sul_tasto,
    tremolo_bow,
    with_brushes,
    with_mallets,
    with_rods,
    # v170 pitch/dynamics utilities
    double_octave,
    dynamics,
    octave_down,
    octave_up,
    velocity_curve,
)
from .export import export_flac, export_mp3, export_ogg, export_wav
from .flow import FlowBeat, apply_flow_to_lyrics, flow_summary, generate_flow
from .mastering import (
    dither,
    master_audio,
    measure_lufs,
    normalize_lufs,
    stereo_analysis,
    true_peak_limit,
)
from .midi import export_midi, import_midi
from .effects import (
    amp_cabinet,
    auto_pan,
    comb_filter,
    console_warmth,
    convolver,
    crossfeed,
    ducking_delay,
    dynamic_eq,
    filter_envelope,
    flanger,
    freq_shift,
    granular_delay,
    haas_stereo,
    impact,
    laser_zap,
    midside_eq,
    multiband_stereo,
    multitap_delay,
    multiband_compress,
    noise_gate,
    noise_riser,
    parallel_compress,
    parametric_eq,
    phaser,
    pitch_correct,
    reverse_reverb,
    ring_mod,
    saturator,
    sidechain,
    delay_throw,
    envelope_follower,
    mono_check,
    reference_match,
    spectrum_analyze,
    stereo_rotate,
    sub_harmonics,
    stereo_width,
    stutter,
    tape_emulation,
    transient_shaper,
    vocal_doubler,
    volume_shaper,
    waveshaper,
)
from .integrations import (
    ai_generate_melody,
    ai_generate_sound,
    analyze_audio,
    from_music21,
    from_pretty_midi,
    import_audio,
    list_integrations,
    register_ai_backend,
    register_synth_plugin,
    to_music21,
)
from .export import QUALITY_PRESETS, export_with_preset, list_quality_presets
from .auto_mix import (
    auto_mix,
    auto_level,
    auto_pan_placement,
    auto_eq_carve,
    fade_in,
    fade_out,
    swell,
)
from .notation import export_abc, export_lilypond, export_musicxml
from .rhythm_game import export_clone_hero, export_stepmania
from .transform import (
    GENRE_PROFILES,
    GenreProfile,
    apply_rhythm_pattern,
    articulation_transform,
    dynamics_transform,
    genre_transform,
    groove_transform,
    harmony_transform,
    instrument_transform,
    list_genres,
    list_rhythm_patterns,
    rhythm_transform,
)
from .symphony import (
    BIG_BAND_SECTIONS,
    FAMILIES,
    INSTRUMENT_RANGES,
    SCORE_ORDER,
    TRANSPOSING_INSTRUMENTS,
    Movement,
    Part,
    Symphony,
    get_family,
    orchestrate,
    orchestrate_big_band,
    score_sort_key,
)
from .pattern import Pattern
from .playback import play
from .plugins import (
    discover_plugins,
    get_effect,
    get_generator,
    get_instrument,
    plugin_summary,
    register_effect,
    register_generator,
    register_instrument,
)
from .plugins import (
    list_effects as list_plugin_effects,
)
from .plugins import (
    list_generators as list_plugin_generators,
)
from .plugins import (
    list_instruments as list_plugin_instruments,
)
from .serialization import song_from_json, song_to_json
from .sound_design import SoundDesigner, Timbre, Wavetable
from .synth import Synth
from .theory import (
    Change,
    SongTemplate,
    accent_pattern,
    additive_rhythm,
    aksak,
    ambiguity_score,
    analysis_report,
    analyze_arrangement,
    analyze_harmony,
    andalusian_cadence,
    apply_groove,
    approach_pattern,
    arpeggiate_chord,
    arpeggio_pattern,
    augment,
    augmented_sixth,
    auto_accompany,
    auto_arrange,
    auto_octave,
    available_notes,
    available_tensions,
    avoid_notes,
    backing_track,
    bass_line_funk,
    bass_line_jazz,
    bass_line_latin,
    blues_lick,
    build_transition_matrix,
    call_and_response,
    canon,
    cents_from_et,
    chain_patterns,
    change_key,
    check_parallel_fifths,
    chord_extensions,
    chord_interpolation,
    chord_relationships,
    chord_scale,
    chord_tones,
    chords_per_bar,
    chromatic_run,
    classical_minuet,
    classify_genre,
    classify_interval,
    click_track,
    coltrane_changes,
    common_intervals,
    comp_pattern,
    compare_progressions,
    compare_songs,
    complexity_contrast,
    complexity_curve,
    complexity_score,
    compose,
    consonance_score,
    continue_in_style,
    contour_match,
    contour_string,
    contrary_motion_ratio,
    corpus_stats,
    count_pitch_classes,
    count_syllables,
    critique,
    critique_song,
    deceptive_cadence,
    density_contrast,
    density_plan,
    density_profile,
    detect_cadences,
    detect_inversion,
    detect_modulations,
    detect_phrases,
    detect_repeated_sections,
    detect_sections,
    detune_to_just,
    develop_motif,
    dice_game,
    diminish,
    diminished_run,
    direct_modulation,
    displace,
    dorian_lick,
    dotted,
    double_at_octave,
    double_dotted,
    double_time,
    drone,
    duration_stats,
    dynamics_curve,
    dynamics_map,
    ear_training_chords,
    ear_training_intervals,
    enharmonic_equivalent,
    evolving_pad,
    extend_progression,
    extract_groove,
    fill_leaps,
    filter_chord_tones,
    find_pivot_chords,
    find_similar_melodies,
    find_similar_progressions,
    find_similar_progressions_dna,
    fit_to_range,
    format_chord,
    format_progression,
    fragment,
    functional_analysis,
    generate_canon,
    generate_countermelody,
    generate_form,
    generate_from_matrix,
    generate_fugue,
    generate_full_song,
    generate_period,
    generate_phrase,
    generate_polyrhythm,
    generate_progression,
    generate_rhythm_pattern,
    generate_rondo,
    generate_scale_melody,
    generate_sonata_form,
    generate_theme_and_variations,
    get_pattern,
    grade_counterpoint,
    grade_lesson,
    grade_quiz,
    groove_template,
    half_time,
    hammer_on,
    harmonic_field,
    harmonic_rhythm,
    harmonic_skeleton,
    harmonize_melody,
    hemiola,
    hocket,
    humanize_timing,
    humanize_velocity,
    in_range,
    instrument_range,
    interval_name,
    interval_sequence,
    interval_vector,
    inversion_label,
    invert_chord,
    irrational_meter,
    is_chord_tone,
    just_ratio,
    key_certainty,
    key_distribution,
    key_signature_accidentals,
    label_form,
    leap_count,
    leap_step_ratio,
    legato_connect,
    list_patterns,
    list_scales,
    longest_rest,
    lookup_voicing,
    lydian_run,
    melodic_interval_histogram,
    melodic_range,
    melody_contour,
    melody_similarity,
    melody_summary,
    midi_to_note,
    mixolydian_lick,
    modal_interchange,
    modulation_path,
    morph_chord,
    most_likely_next,
    motif_similarity,
    neapolitan_chord,
    nested_tuplet,
    next_note_distribution,
    normalize_notes,
    note_probability,
    note_range,
    note_to_freq,
    note_to_midi,
    octave_distribution,
    optimal_voicing,
    orchestration_curve,
    ostinato,
    palm_mute,
    parallel_motion,
    parse_chord_line,
    parse_chord_symbol,
    parse_chord_symbols,
    parse_melody_line,
    parse_roman,
    pc_complement,
    pc_intersection,
    pc_set,
    pc_union,
    pedal_point,
    phase_shift,
    phrase_lengths,
    pitch_center,
    pitch_class_histogram,
    pitch_histogram,
    pivot_modulation,
    plagal_cadence,
    polymetric_overlay,
    progression_distance,
    progression_dna,
    progression_from_roman,
    progression_similarity,
    pull_off,
    quantize_harmonic_rhythm,
    quantize_rhythm,
    quartal_voicing,
    quiz_chords,
    quiz_intervals,
    random_voicing,
    reduce_to_chords,
    register_spread,
    reharmonize,
    repetition_ratio,
    respell_note,
    rest_ratio,
    restyle,
    retrograde_rhythm,
    reverse_progression,
    rhythm_changes,
    rhythm_match,
    rhythm_string,
    rhythmic_density,
    rootless_a,
    rootless_b,
    rotate_progression,
    rotate_voicing,
    row_transforms,
    rubato,
    scale_brightness,
    scale_degree,
    scale_degree_name,
    scale_exercise,
    scale_info,
    scale_modes,
    scale_search,
    secondary_dominant,
    section_bars,
    section_similarity_matrix,
    septuplet,
    sequence_by_interval,
    sforzando,
    similar_motion_ratio,
    slide,
    smooth_melody,
    smooth_voicings,
    song_diff,
    song_fingerprint,
    song_form,
    song_from_dsl,
    song_patch,
    song_similarity,
    species_counterpoint,
    split_note,
    step_count,
    stress_pattern,
    stretch_melody,
    stride_voicing,
    string_quartet,
    style_fingerprint,
    suggest_next_chord,
    suggest_scale,
    suggest_substitutions,
    swing_notes,
    swing_quantize,
    target_chord_tones,
    tempo_distribution,
    tempo_trainer,
    tension_at,
    tension_curve,
    tension_story,
    text_to_melody,
    texture_density,
    theory_course,
    thicken_texture,
    thin_texture,
    tied,
    tone_row,
    total_duration,
    train_style_from_corpus,
    transpose_progression,
    transpose_set,
    tritone_sub,
    twelve_bar_blues,
    unique_pitches,
    validate_counterpoint,
    velocity_curve,
    velocity_stats,
    verify_playback,
    voice_independence_score,
    voice_lead_satb,
    voice_progression,
    whole_tone_run,
)
from .vocal import (
    VocalEvent,
    VocalTrack,
    list_tts_backends,
    register_tts_backend,
)
from .voice import Lyrics, VoiceClip, VoiceTrack, detect_backends, list_voices
from .voice import generate as generate_voice

__all__ = [
    "__version__",
    # durations
    "WHOLE",
    "HALF",
    "QUARTER",
    "EIGHTH",
    "SIXTEENTH",
    "THIRTY_SECOND",
    "SIXTY_FOURTH",
    "DOTTED_WHOLE",
    "DOTTED_HALF",
    "DOTTED_QUARTER",
    "DOTTED_EIGHTH",
    "DOTTED_SIXTEENTH",
    "DOUBLE_DOTTED_HALF",
    "DOUBLE_DOTTED_QUARTER",
    # tuplets
    "triplet",
    "tuplet",
    "triplets",
    "tuplets",
    # ornaments
    "trill",
    "mordent",
    "upper_mordent",
    "turn",
    "grace_note",
    "doit",
    "fall",
    "flip",
    "shake",
    # articulations
    "staccato",
    "legato",
    "pizzicato",
    # engine
    "Note",
    "Chord",
    "Beat",
    "Track",
    "Song",
    "Clip",
    "ClipSlot",
    "Section",
    "Session",
    "scale",
    "arp",
    "chord_prog",
    "crescendo",
    "decrescendo",
    "euclid",
    "Pattern",
    "SoundDesigner",
    "Timbre",
    "Wavetable",
    "detect_key",
    "generate_melody",
    "generate_song",
    "humanize",
    "prob",
    "repeat",
    "staccato",
    "transpose",
    "SCALES",
    "CHORD_SHAPES",
    "INTERVALS",
    "ARP_PATTERNS",
    "suggest_progression",
    "PolyphonicTrack",
    "SampleTrack",
    "remix",
    "bpm_ramp",
    "accelerando",
    "ritardando",
    "analyze_progression",
    "voice_lead",
    "multitap_delay",
    "granular",
    "autotune",
    "conv_reverb",
    "eq",
    # synth
    "Synth",
    # theory
    "chord_scale",
    "available_tensions",
    "analyze_harmony",
    "generate_chord_melody",
    "generate_counterpoint",
    "generate_variation",
    "generate_chord_voicing",
    "humanize_velocity",
    "transpose_progression",
    "detect_tempo",
    "scale_info",
    "chord_extensions",
    "merge_tracks",
    "interval_name",
    "parallel_motion",
    "suggest_next_chord",
    "note_range",
    "rhythmic_density",
    "detect_repeated_sections",
    "melody_contour",
    "harmonic_rhythm",
    "consonance_score",
    "normalize_notes",
    "count_pitch_classes",
    "melodic_interval_histogram",
    "invert_chord",
    "rotate_voicing",
    "pedal_point",
    "retrograde_rhythm",
    "stretch_melody",
    "arpeggiate_chord",
    "staccato",
    "legato_connect",
    "swing_notes",
    "accent_pattern",
    "dynamics_curve",
    "call_and_response",
    "ostinato",
    "canon",
    "hocket",
    "sequence_by_interval",
    "chromatic_run",
    "trill",
    "diminished_run",
    "whole_tone_run",
    "blues_lick",
    "arpeggio_pattern",
    "lydian_run",
    "mixolydian_lick",
    "modal_interchange",
    "dorian_lick",
    "phrygian_run",
    "tritone_sub",
    "secondary_dominant",
    "deceptive_cadence",
    "plagal_cadence",
    # v39.0 — chromatic harmony
    "neapolitan_chord",
    "augmented_sixth",
    "picardy_third",
    # v40.0 — rhythm
    "quintuplet",
    "septuplet",
    "generate_polyrhythm",
    "metric_modulation",
    # v41.0 — progression templates
    "twelve_bar_blues",
    "rhythm_changes",
    "coltrane_changes",
    "andalusian_cadence",
    # v42.0 — voice leading
    "voice_lead_satb",
    "check_parallel_fifths",
    # v43.0 — modulation
    "find_pivot_chords",
    "modulation_path",
    "direct_modulation",
    "pivot_modulation",
    # v44.0 — roman numerals
    "parse_roman",
    "progression_from_roman",
    # v45.0 — rhythmic displacement
    "displace",
    "phase_shift",
    "hemiola",
    "additive_rhythm",
    "aksak",
    # v46.0 — counterpoint
    "classify_interval",
    "species_counterpoint",
    # v47.0 — generative melody
    "generate_scale_melody",
    "generate_rhythm_pattern",
    # v48.0 — chord voicings
    "rootless_a",
    "rootless_b",
    "quartal_voicing",
    "stride_voicing",
    # v49.0 — form templates
    "song_form",
    "section_bars",
    # v50.0 — harmonic analysis
    "functional_analysis",
    "detect_cadences",
    # v51.0 — ear training
    "ear_training_intervals",
    "ear_training_chords",
    "scale_exercise",
    # v52.0 — tension curves
    "tension_curve",
    "tension_at",
    # v53.0 — orchestration
    "instrument_range",
    "in_range",
    "double_at_octave",
    "string_quartet",
    # v54.0 — motif development
    "augment",
    "diminish",
    "fragment",
    "motif_similarity",
    # v56.0 — scale atlas
    "list_scales",
    "scale_search",
    "scale_brightness",
    "scale_modes",
    # v58.0 — lyric rhythm
    "count_syllables",
    "stress_pattern",
    "text_to_melody",
    # v59.0 — groove templates
    "groove_template",
    "apply_groove",
    "extract_groove",
    # v60.0 — chord substitution
    "suggest_substitutions",
    "reharmonize",
    # v61.0 — song fingerprinting
    "song_fingerprint",
    "song_similarity",
    # v62.0 — counterpoint validator
    "validate_counterpoint",
    "grade_counterpoint",
    # v63.0 — chord tone targeting
    "target_chord_tones",
    "approach_pattern",
    # v64.0 — multi-tonic
    "tone_row",
    "row_transforms",
    "interval_vector",
    # v65.0 — structure detection
    "section_similarity_matrix",
    "detect_sections",
    "label_form",
    # v66.0 — drone & ambient
    "drone",
    "evolving_pad",
    # v67.0 — complex meters
    "nested_tuplet",
    "irrational_meter",
    "polymetric_overlay",
    # v68.0 — harmonic reduction
    "reduce_to_chords",
    "harmonic_skeleton",
    "complexity_score",
    # v69.0 — dice game
    "dice_game",
    "classical_minuet",
    # v70.0 — microtuning
    "just_ratio",
    "cents_from_et",
    "detune_to_just",
    "quarter_tone",
    # v71.0 — texture density
    "texture_density",
    "thin_texture",
    "thicken_texture",
    # v72.0 — voicing constraints
    "optimal_voicing",
    "smooth_voicings",
    # v73.0 — rhythm quantization
    "quantize_rhythm",
    "swing_quantize",
    "humanize_timing",
    # v74.0 — bass line intelligence
    "bass_line_jazz",
    "bass_line_funk",
    "bass_line_latin",
    # v75.0 — melody harmonization
    "harmonize_melody",
    # v76.0 — practice room
    "click_track",
    "backing_track",
    "tempo_trainer",
    # v77.0 — song statistics
    "corpus_stats",
    "key_distribution",
    "tempo_distribution",
    # v78.0 — melodic patterns
    "list_patterns",
    "get_pattern",
    "chain_patterns",
    # v79.0 — dynamic range
    "sforzando",
    "dynamics_map",
    # v80.0 — progression generator
    "generate_progression",
    "extend_progression",
    # v81.0 — tempo curves
    "ritardando",
    "accelerando",
    "rubato",
    # v82.0 — comping patterns
    "comp_pattern",
    # v83.0 — duration algebra
    "dotted",
    "double_dotted",
    "tied",
    "split_note",
    # v84.0 — instrument techniques
    "hammer_on",
    "pull_off",
    "slide",
    "palm_mute",
    # v85.0 — song comparison
    "compare_progressions",
    # v86.0 — enharmonic
    "enharmonic_equivalent",
    "key_signature_accidentals",
    "respell_note",
    # v87.0 — DSL
    "parse_chord_line",
    "parse_melody_line",
    "song_from_dsl",
    # v88.0 — remix
    "change_key",
    "double_time",
    "half_time",
    # v89.0 — voice independence
    "similar_motion_ratio",
    "contrary_motion_ratio",
    "voice_independence_score",
    # v90.0 — quizzes
    "quiz_intervals",
    "quiz_chords",
    "grade_quiz",
    # v91.0 — density planner
    "density_plan",
    "orchestration_curve",
    # v92.0 — transition matrix
    "build_transition_matrix",
    "most_likely_next",
    "generate_from_matrix",
    # v93.0 — analysis report
    "analysis_report",
    # v94.0 — scale explorer
    "suggest_scale",
    "available_notes",
    "avoid_notes",
    # v95.0 — voicing database
    "lookup_voicing",
    "random_voicing",
    # v96.0 — memory game
    "memory_game",
    "verify_playback",
    # v97.0 — harmonic field
    "harmonic_field",
    "chord_relationships",
    # v98.0 — phrase detection
    "detect_phrases",
    "phrase_lengths",
    # v99.0 — song template
    "SongTemplate",
    # v101.0 — corpus learning
    "train_style_from_corpus",
    "continue_in_style",
    # v102.0 — note probability
    "note_probability",
    "next_note_distribution",
    # v103.0 — chord morphing
    "morph_chord",
    "chord_interpolation",
    # v104.0 — pitch set ops
    "pc_set",
    "pc_union",
    "pc_intersection",
    "pc_complement",
    "transpose_set",
    # v105.0 — density analysis
    "density_profile",
    "density_contrast",
    # v106.0 — harmonic ambiguity
    "ambiguity_score",
    "key_certainty",
    # v107.0 — chord symbol formatter
    "format_chord",
    "format_progression",
    # v108.0 — voice range optimizer
    "fit_to_range",
    "auto_octave",
    # v109.0 — interval sequence
    "interval_sequence",
    "common_intervals",
    # v110.0 — contour matching
    "contour_string",
    "contour_match",
    # v111.0 — rhythm matching
    "rhythm_string",
    "rhythm_match",
    # v112.0 — complexity curve
    "complexity_curve",
    "complexity_contrast",
    # v113.0 — inversion analyzer
    "detect_inversion",
    "inversion_label",
    # v114.0 — note name utilities
    "note_to_midi",
    "midi_to_note",
    "note_to_freq",
    # v115.0 — progression similarity
    "progression_similarity",
    "find_similar_progressions",
    # v116.0 — scale degree naming
    "scale_degree",
    "scale_degree_name",
    # v117.0 — chord tone filter
    "chord_tones",
    "is_chord_tone",
    "filter_chord_tones",
    # v118.0 — melodic range stats
    "melodic_range",
    "pitch_center",
    # v119.0 — pitch histogram
    "pitch_histogram",
    "pitch_class_histogram",
    # v120.0 — velocity stats
    "velocity_stats",
    "velocity_curve",
    # v121.0 — duration stats
    "duration_stats",
    "total_duration",
    # v122.0 — rest analysis
    "rest_ratio",
    "longest_rest",
    # v123.0 — leap/step analysis
    "leap_count",
    "step_count",
    "leap_step_ratio",
    # v124.0 — repetition analysis
    "repetition_ratio",
    "unique_pitches",
    # v125.0 — chord symbol parser
    "parse_chord_symbol",
    "parse_chord_symbols",
    # v126.0 — melody smoothing
    "smooth_melody",
    "fill_leaps",
    # v127.0 — harmonic rhythm
    "chords_per_bar",
    "quantize_harmonic_rhythm",
    # v128.0 — octave distribution
    "octave_distribution",
    "register_spread",
    # v129.0 — progression reversal/rotation
    "reverse_progression",
    "rotate_progression",
    # v130.0 — melody summary
    "melody_summary",
    # v131.0 — theory refactor, genre classifier, full song generator, arrangement engine
    "classify_genre",
    "generate_full_song",
    "generate_countermelody",
    "develop_motif",
    "restyle",
    "auto_arrange",
    # v133.0 — chord voicing AI, phrase generator, tension narrative
    "voice_progression",
    "generate_phrase",
    "tension_story",
    # v134.0 — variation suite, critique, modulation detector
    "generate_theme_and_variations",
    "critique",
    "critique_song",
    "detect_modulations",
    # v139.0 — fugue generator
    "generate_fugue",
    # v135.0 — period builder, guided composition, melodic similarity
    "generate_period",
    "compose",
    # v140.0 — form generators
    "generate_canon",
    "generate_sonata_form",
    "generate_rondo",
    "melody_similarity",
    "find_similar_melodies",
    # v136.0 — form generator, style fingerprint, arrangement analyzer
    "generate_form",
    "style_fingerprint",
    "analyze_arrangement",
    # v137.0 — chord progression DNA, CLI compose + analyze
    "progression_dna",
    "progression_distance",
    "find_similar_progressions_dna",
    # v139.0 — auto-accompaniment, song comparison
    "auto_accompany",
    "compare_songs",
    "theory_course",
    "grade_lesson",
    "quantize_track",
    "render_preview",
    "to_svg_waveform",
    "to_piano_roll",
    "to_spectrogram",
    "to_track_waveforms",
    "suggest_arrangement",
    "to_sheet_music",
    "to_harmonic_rhythm",
    # v151-152 spatial audio
    "spatial_pan",
    "orbit",
    "encode_bformat",
    "decode_bformat",
    "sum_bformat",
    "spatial_mix",
    # v154 plugin system
    "register_instrument",
    "register_effect",
    "register_generator",
    "get_instrument",
    "get_effect",
    "get_generator",
    # v166 vocal + flow
    "VocalTrack",
    "VocalEvent",
    "list_tts_backends",
    "register_tts_backend",
    "generate_flow",
    "apply_flow_to_lyrics",
    "flow_summary",
    "FlowBeat",
    "discover_plugins",
    "plugin_summary",
    "list_plugin_instruments",
    "list_plugin_effects",
    "list_plugin_generators",
    "tempo_map",
    "generate_bass_line",
    "generate_drums",
    "song_diff",
    "song_patch",
    "Change",
    # composition
    "continue_melody",
    "to_lead_sheet",
    "to_tab",
    "song_map",
    "song_summary",
    "parse_song_dsl",
    "song_from_dsl_v2",
    "analyze_song",
    "full_analysis",
    "to_abc",
    "to_html",
    "generate_arrangement",
    "generate_fill",
    "generate_intro",
    "generate_outro",
    "generate_riser",
    "Verse",
    "Chorus",
    "Bridge",
    "Intro",
    "Outro",
    # serialization
    "song_to_json",
    "song_from_json",
    # automation
    "Automation",
    "EnvFollower",
    "ModMatrix",
    "song_overlay",
    "song_append",
    "song_extract",
    # mastering
    "measure_lufs",
    "normalize_lufs",
    "true_peak_limit",
    "dither",
    "stereo_analysis",
    "master_audio",
    # audio export
    "export_wav",
    "export_mp3",
    "export_ogg",
    "export_flac",
    "export_midi",
    "import_midi",
    # notation export
    "export_lilypond",
    "export_abc",
    "export_musicxml",
    # effects
    "EffectsChain",
    "reverb",
    "delay",
    "chorus",
    "distortion",
    "flanger",
    "phaser",
    "bitcrush",
    "multiband_compress",
    "ring_mod",
    "vocoder",
    "tape_sat",
    "lowpass",
    "highpass",
    "bandpass",
    "compress",
    "limiter",
    "pan",
    "sidechain",
    "slapback",
    "stereo_width",
    "tremolo",
    "vibrato",
    "lfo_filter",
    "gate",
    "noise_sweep",
    # playback
    "play",
    # voice
    "Lyrics",
    "VoiceClip",
    "VoiceTrack",
    "generate_voice",
    "detect_backends",
    "list_voices",
]
