#!/usr/bin/env python3
"""DistroKid upload preparation — organize rendered albums for fast batch upload.

DistroKid has no public API. Uploads are manual through their web UI.
This script prepares everything you need in one place so you can move
through the upload form quickly without hunting for files or metadata.

For each album it generates:
  dist/distrokid/<album>/
    audio/           ← FLAC files ready to upload (drag entire folder)
    metadata.txt     ← copy-paste metadata for each track
    checklist.md     ← step-by-step upload checklist

Usage:
    python scripts/distrokid_prep.py --album jazz_neosoul
    python scripts/distrokid_prep.py --all
    make distrokid-prep
    make distrokid-prep-jazz_neosoul
"""

from __future__ import annotations

import argparse
import importlib.util
import shutil
from datetime import date, timedelta
from pathlib import Path

REPO = Path(__file__).parent.parent
DIST = REPO / "dist"

RESET = "\033[0m"
BOLD = "\033[1m"
CYAN = "\033[96m"
GREEN = "\033[92m"
DIM = "\033[2m"


def load_album(stem: str) -> dict:
    spec = importlib.util.spec_from_file_location("_a", REPO / "albums" / f"{stem}.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod.ALBUM


def prep_album(stem: str) -> Path:
    album = load_album(stem)
    out = DIST / "distrokid" / stem
    audio = out / "audio"
    audio.mkdir(parents=True, exist_ok=True)

    title = album["title"]
    artist = album.get("artist", "code-music")
    genre = album["genre"]
    year = album.get("year", date.today().year)
    tracks = album["tracks"]
    # Release date: 2 weeks from now (DistroKid requires future date)
    rel_date = (date.today() + timedelta(days=14)).isoformat()

    print(f"  {BOLD}{CYAN}{title}{RESET}  {DIM}({genre}){RESET}")

    # ── Copy FLAC files into audio/ ────────────────────────────────────────
    flac_dir = DIST / "flac"
    wav_dir = DIST / "wav"
    copied = 0
    for i, track in enumerate(tracks, 1):
        song_stem = track["song"]
        track_title = track.get("title", song_stem.replace("_", " ").title())
        prefix = f"{i:02d} - {track_title}"

        # Prefer FLAC, fall back to WAV
        src_flac = flac_dir / f"{song_stem}.flac"
        src_wav = wav_dir / f"{song_stem}.wav"
        if src_flac.exists():
            dst = audio / f"{prefix}.flac"
            shutil.copy2(src_flac, dst)
            copied += 1
        elif src_wav.exists():
            dst = audio / f"{prefix}.wav"
            shutil.copy2(src_wav, dst)
            copied += 1
        else:
            print(f"    ⚠ {song_stem} not rendered — run: make songs-flac")

    # ── metadata.txt — copy-paste fields for DistroKid form ────────────────
    meta_lines = [
        f"ALBUM: {title}",
        f"ARTIST: {artist}",
        f"GENRE: {genre}",
        f"RELEASE DATE: {rel_date}",
        f"YEAR: {year}",
        "LABEL: Self-released",
        "UPC: (auto-generated by DistroKid)",
        "",
        "TRACKS:",
        "-" * 50,
    ]
    for i, track in enumerate(tracks, 1):
        track_title = track.get("title", track["song"].replace("_", " ").title())
        meta_lines += [
            f"  Track {i:02d}: {track_title}",
            "    ISRC: (auto-generated by DistroKid)",
            "    Explicit: No",
            "    Language: English",
            "    Lyrics: Instrumental",
            "",
        ]
    meta_lines += [
        "-" * 50,
        "DESCRIPTION:",
        album.get("description", ""),
        "",
        "INFLUENCES:",
        *[f"  {inf}" for inf in album.get("influences", [])],
    ]
    (out / "metadata.txt").write_text("\n".join(meta_lines) + "\n")

    # ── checklist.md — step-by-step upload guide ───────────────────────────
    n = len(tracks)
    checklist = f"""# DistroKid Upload Checklist — {title}

## Pre-upload
- [ ] Audio files are in `dist/distrokid/{stem}/audio/` ({copied} files)
- [ ] All tracks rendered (`make songs-flac` if missing)

## Upload at https://distrokid.com/upload/

### Step 1: Album info
- **Type**: Album ({n} tracks)
- **Album title**: `{title}`
- **Artist name**: `{artist}`
- **Release date**: `{rel_date}` (must be future)
- **Genre**: `{genre}`
- **Label**: Self-released
- **Explicit**: No
- **Language**: English

### Step 2: Upload audio
Drag the entire `audio/` folder into the upload area:
```
{audio}
```

### Step 3: Track metadata
"""
    for i, track in enumerate(tracks, 1):
        tt = track.get("title", track["song"].replace("_", " ").title())
        checklist += f"- Track {i:02d}: **{tt}** — Instrumental, English\n"

    checklist += f"""
### Step 4: Review & submit
- [ ] All {n} tracks uploaded
- [ ] Track order is correct
- [ ] Release date is at least 2 weeks out
- [ ] Click "Submit"

### Step 5: Post-upload
- [ ] Note the UPC code DistroKid assigns
- [ ] Set up pre-save link if desired
- [ ] Spotify approval takes 3–5 days
- [ ] Apple Music takes 1–2 weeks

---
Generated by code-music · https://github.com/Talador12/code-music
"""
    (out / "checklist.md").write_text(checklist)

    # ── Cover art ──────────────────────────────────────────────────────────
    cover_src = DIST / "covers" / f"{stem}.png"
    if cover_src.exists():
        shutil.copy2(cover_src, out / "cover.png")
        print("    cover.png copied")

    print(f"    {GREEN}✓ {copied} tracks + metadata + checklist → {out}{RESET}")
    return out


def main() -> None:
    from albums.render import discover_albums

    parser = argparse.ArgumentParser(description="Prepare albums for DistroKid upload")
    parser.add_argument("--album", help="Single album stem")
    parser.add_argument("--all", action="store_true", help="All albums")
    args = parser.parse_args()

    stems = discover_albums() if args.all else ([args.album] if args.album else [])
    if not stems:
        parser.print_help()
        return

    print(f"\n{BOLD}Preparing for DistroKid upload{RESET}\n")
    for stem in stems:
        prep_album(stem)
    print(f"\n{GREEN}{BOLD}✓ Done.{RESET} Upload at https://distrokid.com/upload/\n")


if __name__ == "__main__":
    main()
