"""Euclidean Groove — world-music-inspired rhythms from the Bjorklund algorithm.

Every rhythm is generated by euclid(hits, steps) — mathematically perfect
distributions found in West African drumming, Cuban son, and Brazilian bossa.
"""

from code_music import (
    Chord,
    EffectsChain,
    Song,
    SoundDesigner,
    Track,
    euclid,
    reverb,
)

# -- Custom percussion (SoundDesigner) + built-in instruments ----------------

conga = (
    SoundDesigner("conga")
    .add_osc("sine", volume=0.7)
    .add_osc("triangle", detune_cents=700, volume=0.2)
    .noise("white", volume=0.15, seed=30)
    .envelope(attack=0.001, decay=0.15, sustain=0.0, release=0.1)
    .filter("bandpass", cutoff=400, resonance=1.5)
    .pitch_envelope(start_multiplier=2.0, end_multiplier=1.0, duration=0.01)
)

shaker = (
    SoundDesigner("shaker")
    .noise("white", volume=0.8, seed=50)
    .envelope(attack=0.001, decay=0.05, sustain=0.0, release=0.03)
    .filter("highpass", cutoff=6000, resonance=0.5)
)

# -- Song --------------------------------------------------------------------

song = Song(title="Euclidean Groove", bpm=105, sample_rate=44100)

song.register_instrument("conga", conga)
song.register_instrument("shaker", shaker)

E = 0.5  # eighth note

# Kick: tresillo (3 in 8) — the most fundamental Afro-Cuban pattern
tr_kick = song.add_track(Track(name="kick", instrument="drums_kick", volume=0.75))
for _ in range(4):
    tr_kick.extend(euclid(3, 8, "C", 2, E))

# Conga: (5 in 8) — classic West African
tr_conga = song.add_track(Track(name="conga", instrument="conga", volume=0.5))
for _ in range(4):
    tr_conga.extend(euclid(5, 8, "G", 3, E))

# Shaker: (7 in 8) — almost continuous, one gap
tr_shaker = song.add_track(Track(name="shaker", instrument="shaker", volume=0.3))
for _ in range(4):
    tr_shaker.extend(euclid(7, 8, "C", 6, E))

# Snare: (2 in 8, rotated) — backbeat-ish
tr_snare = song.add_track(Track(name="snare", instrument="drums_snare", volume=0.5))
for _ in range(4):
    tr_snare.extend(euclid(2, 8, "D", 4, E, rotation=2))

# Bass: (3 in 16) — sparse, deep
tr_bass = song.add_track(Track(name="bass", instrument="bass", volume=0.55))
for root in ["C", "F", "G", "C"]:
    tr_bass.extend(euclid(3, 16, root, 2, 0.25))

# Pad: sustained chords
tr_pad = song.add_track(Track(name="pad", instrument="pad", volume=0.3, pan=-0.1))
tr_pad.add(Chord("C", "min7", 3, duration=4.0))
tr_pad.add(Chord("F", "min7", 3, duration=4.0))
tr_pad.add(Chord("G", "min7", 3, duration=4.0))
tr_pad.add(Chord("C", "min7", 3, duration=4.0))

song.effects = {
    "pad": EffectsChain().add(reverb, room_size=0.6, wet=0.25),
    "conga": EffectsChain().add(reverb, room_size=0.3, wet=0.15),
}
