"""Form Showcase - sonata form generated by generate_form."""

from code_music.theory import generate_form

# Generate a complete sonata form with development modulations
song = generate_form(
    "sonata",
    key="D",
    bpm=108,
    chords_per_phrase=4,
    include_melody=True,
    seed=777,
)
