"""Mozart Dice — a minuet generated by the 1787 dice game algorithm."""

from code_music import Chord, EffectsChain, Note, Song, Track, reverb
from code_music.theory import classical_minuet

song = Song(title="Mozart Dice", bpm=120, time_sig=(3, 4))

# Generate a minuet — the original algorithmic composition
melody = classical_minuet(key="G", octave=5, seed=1787)

lead = song.add_track(Track(name="lead", instrument="piano", volume=0.5, pan=0.1))
lead.extend(melody)

# Simple accompaniment in G major
acc = song.add_track(Track(name="acc", instrument="organ", volume=0.35, pan=-0.15))
chords = [("G", "maj"), ("D", "dom7"), ("C", "maj"), ("G", "maj")]
for _ in range(4):
    for root, shape in chords:
        acc.add(Chord(root, shape, 3, duration=3.0))

# Cello bass line
bass = song.add_track(Track(name="bass", instrument="bass", volume=0.45))
for _ in range(4):
    for root, _ in chords:
        bass.extend(
            [Note(root, 2, 1.0), Note(root, 3, 0.5), Note(root, 3, 0.5), Note(root, 2, 1.0)]
        )

song.effects = {
    "lead": EffectsChain().add(reverb, room_size=0.5, wet=0.25),
    "acc": EffectsChain().add(reverb, room_size=0.5, wet=0.25),
}
